#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/lib.sh"
source "$SCRIPT_DIR/config.sh"

# Local release: mint the tag, then build a signed, notarized, stapled .dmg.
#
# The blanket refusal that used to sit here is gone as of #306, because the
# thing it was refusing over now exists: `scripts/build.sh --sign --notarize`
# produces a distributable artifact, and this script's pre-flight is what makes
# minting a tag for it safe.
#
# **This mints and pushes a real tag.** There is no dry run by accident — use
# `--skip-mint` to exercise the build path without one (below).
#
# What this is, and what it is not, so nobody reads a green run as more than it
# is. #307, #308 and #15 have all since landed, so the gaps are narrower now:
#   * This is the LOCAL mint-and-build path (§4 mode 2). release.yml (#307) is
#     the same build on CI against the `prd` environment, and it is what a real
#     release goes through — the tag this mints is what triggers it.
#   * The update feed (#308) is generated by publish-feed.yml when the DRAFT
#     release is *published*, never by this script and never at build time.
#     A .dmg built here and never released still tells no one about the next one.
#   * macOS only, locally. release.yml's second leg is the Windows installer
#     and its third (#390) the agent's four binaries, two of them linux-musl;
#     there is no Linux cockpit build.
#
# Signing and notarization live in build.sh, not here, and that is deliberate:
# they have to run AFTER the CFBundleVersion stamp (editing Info.plist breaks
# the signature), and putting them beside the stamp is what keeps the ordering
# reviewable. It also means the whole distributable path is exercisable with
# `./dev build --release --notarize` — no tag, no mint, no release.

# Publish a release — the repo's §4 mode-2 LOCAL MINT (org Versioning spec
# v1.0; docs/VERSIONING.md). The version is CalVer derived from git by
# scripts/get-version-info.sh; there is no version bump, no version commit,
# and nothing to keep in sync — the old semver --bump flow and the
# config.sh/project.yml verified-in-sync duplicate pair are gone (issue #98).
#
# Flow: pre-flight guards → CI-green check → Sentry DSN → updater signing key
# → tests → mint (probe/reuse/bump ladder, creates + pushes the vYYYY.M.P tag)
# → Release build stamped with the MINTED version. Two credentials are gated
# before the mint (#402) — the Sentry DSN and the updater signing key pair — so
# a missing one costs a re-run, never a pushed tag; the App Store Connect
# triple and the Developer ID identity are still build.sh's to check, after
# the mint — a gap of the same shape, deliberately outside #402's scope. The
# tag lands before the build on purpose: if the build
# fails, re-running publish reuses the same tag idempotently (§4 same-commit
# reuse — within the same UTC month; the derivation is wall-clock, so after a
# roll it mints a new train instead) — the same order a CI mint would use.

# Default values
SKIP_TESTS=0
SKIP_SENTRY=0
SKIP_MINT=0

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --skip-tests)
            SKIP_TESTS=1
            shift
            ;;
        --skip-sentry)
            SKIP_SENTRY=1
            shift
            ;;
        --skip-mint)
            # Exercise the whole signed-and-notarized build WITHOUT minting or
            # pushing a tag. This is how #306's path was verified end to end
            # without cutting the repo's first release: everything below runs,
            # the version comes from the same derivation the mint would have
            # used, and no permanent tag is created.
            SKIP_MINT=1
            shift
            ;;
        --bump)
            log_error "--bump is gone: versions are CalVer minted from git (docs/VERSIONING.md)."
            exit 1
            ;;
        *)
            log_error "Unknown option: $1"
            exit 1
            ;;
    esac
done

log_info "Publishing $APP_NAME"

# --- Pre-flight guards: fail before mutating anything ---------------------

# Ensure clean working tree
ensure_clean_working_tree

# Ensure on main branch
ensure_main_branch

# Verify local main is up to date with origin BEFORE minting — never tag a
# stale local HEAD.
log_info "Checking local main is up to date with origin..."
git fetch origin main
LOCAL_HEAD="$(git rev-parse HEAD)"
REMOTE_HEAD="$(git rev-parse origin/main)"
if [[ "$LOCAL_HEAD" != "$REMOTE_HEAD" ]]; then
    if git merge-base --is-ancestor "$REMOTE_HEAD" "$LOCAL_HEAD"; then
        log_error "Local main is ahead of origin/main (unpushed commits). Push them first."
    else
        log_error "Local main is not up to date with origin/main."
        log_error "Run 'git pull --ff-only' and re-run publish."
    fi
    exit 1
fi

# §4 mode 2: a local mint MUST verify default-branch CI is green before
# tagging. Fail closed — no gh, no verdict, no run found ⇒ no mint.
log_info "Verifying CI is green for $LOCAL_HEAD..."
if ! command_exists gh; then
    log_error "gh CLI is required to verify CI before minting (brew install gh)."
    exit 1
fi
CI_GREEN_COUNT="$(gh run list --workflow CI --commit "$LOCAL_HEAD" \
    --json status,conclusion \
    --jq '[.[] | select(.status == "completed" and .conclusion == "success")] | length')" || {
    log_error "Could not query CI runs for $LOCAL_HEAD (gh error). Refusing to mint blind."
    exit 1
}
if [[ "${CI_GREEN_COUNT:-0}" -lt 1 ]]; then
    log_error "No green 'CI' workflow run found for $LOCAL_HEAD."
    log_error "Wait for CI on main to pass (gh run list --workflow CI --commit $LOCAL_HEAD) and re-run."
    exit 1
fi
log_success "CI is green for HEAD"

# Resolve the Sentry DSN (issue #75).
#
# **This block reaches a real consumer as of #309**, and #306 is where that was
# resolved. It described a dead path for one release cycle and no longer does:
# the note that used to sit here — "no `sentry` crate in any manifest, no panic
# hook, reads an environment variable that reaches nothing" — was true when #277
# wrote it and stopped being true when `crates/crashreport` landed.
#
# The consumer is `crashreport::BUILD_DSN`, which is `option_env!("SENTRY_DSN")`
# — read at COMPILE time, from the environment cargo inherits, which is what the
# `export` below provides. It is deliberately not read at runtime: the SDK's own
# `apply_defaults` would happily take a `SENTRY_DSN` out of the user's shell,
# and an environment variable that can redirect this app's crash reports to a
# third party is not something to leave lying around.
#
# The gate is kept, not because a DSN-less build is broken — it is a silent
# no-op, and that is the common case for a local build — but because a
# *release* that cannot receive a report the operator opted into is a release
# nobody can debug. `--skip-sentry` is the deliberate way past it.
#
# A DSN still reports nothing on its own: crash reporting is opt-in and off in
# a fresh store (#18, #309). This makes reports possible, not automatic.
#
# Checked in pre-flight, so a missing DSN fails before the tag is minted and
# pushed rather than after. Never log the value.
if [[ $SKIP_SENTRY -eq 1 ]]; then
    SENTRY_DSN=""
    log_warning "--skip-sentry: releasing without a DSN (Sentry will no-op in this build)."
elif [[ -n "${SENTRY_DSN:-}" ]]; then
    log_info "Using SENTRY_DSN from the environment"
else
    log_error "SENTRY_DSN is not set, so this release would ship without crash reporting."
    log_error "Locally: put it in .envrc.local and let direnv export it (see .envrc)."
    log_error "In CI: set it from the workflow's secrets."
    log_error "Or pass --skip-sentry to release deliberately without one."
    exit 1
fi
# Exported so the compile below inherits it. build.sh never names SENTRY_DSN;
# it does not have to — `option_env!` reads the environment cargo was invoked
# with, and crashreport's build.rs declares the rerun dependency so changing the
# value actually rebuilds the crate rather than reusing a cached one.
export SENTRY_DSN

# Resolve the updater signing key (issue #402).
#
# `build.sh --release --notarize` always builds the updater payload — the
# minisigned `.app.tar.gz` (#308) — and `make_updater_archive` refuses without
# `TAURI_SIGNING_PRIVATE_KEY`. That refusal is correct: a tarball the feed
# cannot verify is not an update. But it lands LAST — after the tag is minted
# and pushed, after the universal build, after signing, after notarization was
# accepted, and after both the .dmg and the .app were stapled and validated.
# That is where `v2026.9.8` found out on 2026-09-11, under a `doppler run
# --only-secrets` that named every variable `.envrc` and `docs/SECRETS.md`
# listed — and the list did not carry this one.
#
# So it is checked here, in the same place and the same shape as SENTRY_DSN:
# fail closed before `get-version-info.sh --tag --push`, where a missing key
# costs nothing but a re-run. build.sh's own check stays as the last line of
# defence; this one is what keeps a local publish from ever reaching it.
#
# There is deliberately no `--skip-updater-signing`. A publish without the key
# cannot finish either way — the only question was when it found out — so a
# third opt-out would only defer the identical failure back to build.sh.
# `--skip-mint` remains the rehearsal seam, and it is gated identically: it
# builds the same signed artifact.
#
# The key must be non-empty; the password must be SET, and may be empty. An
# unencrypted key has no password, and build.sh exports an empty one for the
# reason its comment gives (unset, an encrypted key makes the signer prompt on
# a tty). But "unset" here is not "unencrypted key" — it is the operator's
# `--only-secrets` list missing a name, the exact shape of the #402 failure —
# and release.yml's preflight requires this password non-empty for the prd
# key, so a local run without it would fail in make_updater_archive, after
# everything. An unencrypted key says so explicitly:
# `TAURI_SIGNING_PRIVATE_KEY_PASSWORD=""`. Neither is defaulted here; build.sh
# keeps its own default as the last line of defence. Nothing in this script
# assigns either name, so they reach build.sh exactly as the environment
# delivered them — no `export` needed, unlike SENTRY_DSN, which `--skip-sentry`
# assigns above. Never log either value.
SIGNING_RECIPE="doppler run --project solador --config prd --no-fallback --only-secrets SENTRY_DSN,APPLE_ASC_KEY_ID,APPLE_ASC_ISSUER_ID,APPLE_ASC_KEY_BASE64,TAURI_SIGNING_PRIVATE_KEY,TAURI_SIGNING_PRIVATE_KEY_PASSWORD -- ./dev publish"
if [[ -z "${TAURI_SIGNING_PRIVATE_KEY:-}" ]]; then
    log_error "the updater payload needs the minisign signing key: TAURI_SIGNING_PRIVATE_KEY unset"
    log_error "source it from Doppler solador/prd (#305): $SIGNING_RECIPE"
    log_error "Checked in pre-flight, so this cost a re-run and no tag was minted."
    exit 1
fi
if [[ -z "${TAURI_SIGNING_PRIVATE_KEY_PASSWORD+set}" ]]; then
    log_error "TAURI_SIGNING_PRIVATE_KEY_PASSWORD is unset; the signer needs it SET (empty is allowed, for an unencrypted key)."
    log_error "source it from Doppler solador/prd beside the key (#305): $SIGNING_RECIPE"
    log_error "Checked in pre-flight, so this cost a re-run and no tag was minted."
    exit 1
fi
log_info "Using TAURI_SIGNING_PRIVATE_KEY and its password from the environment"

# Run tests unless skipped
if [[ $SKIP_TESTS -eq 0 ]]; then
    log_info "Running tests..."
    "$SCRIPT_DIR/test.sh"
fi

# --- Mint (§4): resolve the collision-free version and push the tag -------

if [[ $SKIP_MINT -eq 1 ]]; then
    # Same derivation the mint would have started from, so the artifact is
    # stamped exactly as a real release would stamp it — it simply carries no
    # tag. Never let this branch invent a version of its own.
    VERSION="$("$SCRIPT_DIR/get-version-info.sh" --version)"
    TAG=""
    ACTION="skipped"
    log_warning "--skip-mint: building $VERSION without minting or pushing a tag"
else
log_info "Minting release tag (probe/reuse/bump ladder)..."
MINT_OUTPUT="$("$SCRIPT_DIR/get-version-info.sh" --tag --push)"
VERSION="$(printf '%s\n' "$MINT_OUTPUT" | sed -n 's/^version=//p')"
TAG="$(printf '%s\n' "$MINT_OUTPUT" | sed -n 's/^tag=//p')"
ACTION="$(printf '%s\n' "$MINT_OUTPUT" | sed -n 's/^action=//p')"
if [[ -z "$VERSION" || -z "$TAG" || -z "$ACTION" ]]; then
    log_error "Mint output contract violated (got: $MINT_OUTPUT)"
    exit 1
fi
log_success "Minted $TAG ($ACTION)"
fi

# --- Build: every consumer reads the minted output (§4) -------------------

# Pin the minted version for the build so the artifact is stamped with exactly
# the version the tag carries — build.sh must not re-resolve it (the re-derive
# would diverge the day the bump ladder first fires).
log_info "Building release version $VERSION..."
MARKETING_VERSION="$VERSION" "$SCRIPT_DIR/build.sh" --release --notarize

# --- Epilogue: what this run did, and what it did not ---------------------
#
# Mode-aware, and careful about asynchrony. Until #395 this block told the
# operator that "there is still no automated release pipeline (#307) and no
# update feed (#308)" and printed a `gh release create` to run by hand — after
# the tag it had just pushed had already started release.yml, whose legs create
# that very draft. The hand-rolled command would have raced the workflow
# (`gh release create` fails on an existing release), and the guidance
# described a repo that had stopped existing months earlier. `.envrc` carried
# the same falsehood and #389 fixed it there; this is the same defect one file
# over, and worse, because it is printed on every successful publish.
#
# What this script has NOT observed, and so must not claim: that release.yml
# ran, succeeded, or created the draft — nor, on --skip-mint, that no draft
# exists for the version it stamped (that arm derives the version without
# probing tags, so an earlier push may well have released it). The workflow is
# triggered by the tag push, it is asynchronous, and it waits on the `prd`
# environment's required reviewer TWICE (release.yml's RUNBOOK NOTE): once for
# the two cockpit legs, again for the agent's sign-and-attach job. So the
# tagged branch names what a push *triggers* and where to look, never a
# result; a `reuse` mint pushed nothing and says so; and an action this block
# does not recognise claims nothing rather than falling through to "pushed".

if [[ -n "$TAG" ]]; then
    log_success "Built $APP_NAME $VERSION locally (tag $TAG, mint action: $ACTION)"
else
    log_warning "Built $APP_NAME $VERSION locally — no tag was minted or pushed (--skip-mint)"
fi

# Under the universal target the bundle lives beneath the triple (#335), not at
# target/release/bundle. Read from config.sh so this cannot drift from build.sh.
# `|| true` keeps the no-match case on the fallback line below: under pipefail
# an empty glob fails `ls`, and the assignment would abort the script before
# the guidance it introduces ever rendered.
DMG="$(ls -t "$SCRIPT_DIR/../target/$MACOS_UNIVERSAL_TARGET/release/bundle/dmg/"*.dmg 2>/dev/null | head -1 || true)"
log_info ""
log_info "Signed, notarized and stapled:"
log_info "  ${DMG:-<no .dmg found — check the build output above>}"
log_info ""
log_info "Verify it on a machine that did NOT build it — stapling is what makes"
log_info "that check work offline, and it is the only honest test of it."
log_info ""

if [[ -n "$TAG" ]]; then
    case "$ACTION" in
        create)
            log_info "Pushing $TAG is what triggers .github/workflows/release.yml."
            ;;
        reuse)
            log_info "$TAG already pointed at HEAD, so it was reused, not pushed again."
            log_info "If release.yml ran for this tag, its ORIGINAL push triggered it —"
            log_info "this run pushed nothing and started nothing."
            ;;
        *)
            log_warning "The mint reported action '$ACTION' for $TAG, which this epilogue"
            log_warning "does not know, so it is not claiming the tag was pushed this run."
            log_info "A v* tag push is what triggers .github/workflows/release.yml."
            ;;
    esac
    log_info "That workflow builds the release on CI and attaches all of it to a"
    log_info "DRAFT release: the macOS .dmg and updater payload, the Windows"
    log_info "installer, and the agent's four binaries. It is asynchronous and this"
    log_info "script has not observed it. The .dmg above is this machine's build;"
    log_info "what users download is whatever release.yml attaches."
    log_info ""
    log_info "  1. Approve the 'prd' deployment — TWICE. The reviewer is prompted at"
    log_info "     the start for the two cockpit legs, and again partway through for"
    log_info "     'Sign and attach the agent binaries' (its build and verify jobs"
    log_info "     start unprompted). The draft is not complete until that second"
    log_info "     approval has run; a run that looks stalled is waiting on it."
    log_info "       gh run list --workflow=release.yml --branch $TAG"
    log_info "  2. Review the draft once every leg has uploaded to it:"
    log_info "       gh release view $TAG"
    log_info "  3. Publish the draft when you are happy — as a normal release, not a"
    log_info "     pre-release. Publishing is what triggers"
    log_info "     .github/workflows/publish-feed.yml, which generates latest.json —"
    log_info "     the macOS in-app update feed; it skips pre-releases — and, behind"
    log_info "     ONE MORE 'prd' approval, the agent's signed agent-latest.json"
    log_info "     (#391). Windows has no in-app updater: its users download the"
    log_info "     next installer. A draft's assets are not public until then."
    log_info ""
    log_info "Neither workflow is month-bound. release.yml's every leg and"
    log_info "publish-feed.yml's desktop feed job assert the tag by re-running the"
    log_info "mint's own ladder read-only, pinned to the tag's month (#404), so a"
    log_info "re-run of release.yml for $TAG after the UTC month rolls passes, and"
    log_info "so does a tag the ladder bumped past the bare derivation; each build"
    log_info "leg then pins its artifact to the tag's number and reads it back out."
    log_info "To redo a failed leg (a failed remote tag probe included — that one"
    log_info "is only a re-run), re-run that workflow run — NOT ./dev publish: its"
    log_info "own mint is wall-clock, so after a roll it would not reuse $TAG but"
    log_info "mint the new month's floor slot at the same commit, a second release of this"
    log_info "HEAD. Tags rejected before #404 landed are tidied per the recipe in"
    log_info "that issue's comments; this epilogue deliberately prints no delete"
    log_info "command."
else
    log_info "--skip-mint: this was a local artifact build. This run pushed no tag"
    log_info "and triggered nothing — not release.yml, not publish-feed.yml. If a"
    log_info "release for v$VERSION exists, an earlier tag push made it, and this"
    log_info "build is not it. To cut a release, re-run without --skip-mint."
fi
